arcs:
  alfa:
    ? !!python/tuple
    - 0
    - 0
    : !!python/object:classes.arc.Arc
      cost: 0
      endNode: &id003 !!python/object:classes.node.EvaArea
        clas: 0
        evaDemand: 1
        id: &id001 !!python/name:builtins.id ''
        position:
        - 24
        - 12
        selfEva: 0
        type: evaArea
      flow: 0
      isLegit: 0
      length: 4.2
      resource: null
      startNode: &id002 !!python/object:classes.node.Node
        clas: 1
        id: *id001
        position:
        - 3
        - 49
        type: source
      type: alfa
    ? !!python/tuple
    - 0
    - 1
    : !!python/object:classes.arc.Arc
      cost: 0
      endNode: &id005 !!python/object:classes.node.EvaArea
        clas: 0
        evaDemand: 1
        id: *id001
        position:
        - 19
        - 6
        selfEva: 0
        type: evaArea
      flow: 0
      isLegit: 0
      length: 4.5
      resource: null
      startNode: *id002
      type: alfa
  beta:
    ? !!python/tuple
    - 0
    - 0
    - 0
    - 0
    : !!python/object:classes.arc.Arc
      cost: 0
      endNode: &id004 !!python/object:classes.node.PickDropPoint
        clas: 0
        id: *id001
        position:
        - 45
        - 25
        type: pick_up
      flow: 1
      isLegit: 0
      length: 2.4
      resource: null
      startNode: *id003
      trip: 0
      type: beta
    ? !!python/tuple
    - 0
    - 0
    - 1
    - 0
    : !!python/object:classes.arc.Arc
      cost: 0
      endNode: *id004
      flow: 1
      isLegit: 0
      length: 3.2
      resource: null
      startNode: *id005
      trip: 0
      type: beta
  delta:
    ? !!python/tuple
    - 0
    - 0
    - 0
    - 0
    : !!python/object:classes.arc.Arc
      cost: 2
      endNode: *id004
      flow: 38.5
      isLegit: 1
      length: 6.8
      resource: &id007 !!python/object:classes.resource.Resource
        capacity: 77
        clas: 0
        emptySpeed: 6.0
        fixedCost: 9000
        index: 18
        initialLocation: &id009 !!python/object:classes.node.Node
          clas: 0
          id: *id001
          position:
          - 14
          - 97
          type: initial
        loadedSpeed: 4.62
        loadingTime: 15
        maxTrips: 1
        scenarios: 1
        speed: 40
        timeToAvaiability: 19
        trip: 0
        unloadingTime: 11
        varCost: 1.8
      startNode: &id006 !!python/object:classes.node.PickDropPoint
        clas: 0
        id: *id001
        position:
        - 84
        - 81
        type: shelter
      trip: 0
      type: delta
  epsilon:
    ? !!python/tuple
    - 0
    - 0
    : !!python/object:classes.arc.Arc
      cost: 0
      endNode: &id008 !!python/object:classes.node.Node
        clas: 1
        id: *id001
        position:
        - 95
        - 50
        type: sink
      flow: 10
      isLegit: 0
      length: 3.2
      resource: null
      startNode: *id006
      type: epsilon
  gamma:
    ? !!python/tuple
    - 0
    - 0
    - 0
    - 0
    : !!python/object:classes.arc.Arc
      cost: 2
      endNode: *id006
      flow: 38.5
      isLegit: 1
      length: 6.8
      resource: *id007
      startNode: *id004
      trip: 0
      type: gamma
  lmbda:
    ? !!python/tuple
    - 0
    - 0
    : !!python/object:classes.arc.Arc
      cost: 0
      endNode: *id008
      flow: 0
      isLegit: 0
      length: 8.0
      resource: null
      startNode: *id003
      type: lmbda
    ? !!python/tuple
    - 1
    - 0
    : !!python/object:classes.arc.Arc
      cost: 0
      endNode: *id008
      flow: 0
      isLegit: 0
      length: 8.7
      resource: null
      startNode: *id005
      type: lmbda
  zeta:
    ? !!python/tuple
    - 0
    - 0
    - 0
    : !!python/object:classes.arc.Arc
      cost: 2
      endNode: *id004
      flow: 0
      isLegit: 1
      length: 7.8
      resource: *id007
      startNode: *id009
      trip: 0
      type: zeta
nodes:
  area:
  - *id003
  - *id005
  initial:
  - *id009
  pick_up:
  - *id004
  shelter:
  - *id006
  sink: *id008
  source: *id002
params:
  a: 2
  b: 1
  c: 1
  demand: 1
  h: 1
  i: 1
  k: 1
  self: 0
resources:
- *id007
