arcs:
  alfa:
    ? !!python/tuple
    - 0
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: &id001 !!python/object:node.EvaArea
        clas: 0
        evaDemand: 187
        id: 0
        position:
        - 27
        - 83
        selfEva: 0
        type: evaArea
      flow: 0
      length: 4.1
      resource: null
      startNode: &id007 !!python/object:node.Node
        clas: 0
        id: 1
        position:
        - 3
        - 49
        type: source
      type: alfa
  beta:
    ? !!python/tuple
    - 0
    - 0
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: &id002 !!python/object:node.PickDropPoint
        clas: 0
        id: 0
        position:
        - 35
        - 89
        type: pick_up
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 0
      type: beta
    ? !!python/tuple
    - 0
    - 1
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 1
      type: beta
    ? !!python/tuple
    - 0
    - 2
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 2
      type: beta
    ? !!python/tuple
    - 0
    - 3
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 3
      type: beta
    ? !!python/tuple
    - 0
    - 4
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 4
      type: beta
    ? !!python/tuple
    - 0
    - 5
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 5
      type: beta
    ? !!python/tuple
    - 0
    - 6
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 6
      type: beta
    ? !!python/tuple
    - 0
    - 7
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 7
      type: beta
    ? !!python/tuple
    - 0
    - 8
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 8
      type: beta
    ? !!python/tuple
    - 0
    - 9
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 9
      type: beta
    ? !!python/tuple
    - 0
    - 10
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 10
      type: beta
    ? !!python/tuple
    - 0
    - 11
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 11
      type: beta
    ? !!python/tuple
    - 0
    - 12
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 12
      type: beta
    ? !!python/tuple
    - 0
    - 13
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 13
      type: beta
    ? !!python/tuple
    - 0
    - 14
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 14
      type: beta
    ? !!python/tuple
    - 0
    - 15
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 15
      type: beta
    ? !!python/tuple
    - 0
    - 16
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 16
      type: beta
    ? !!python/tuple
    - 0
    - 17
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 17
      type: beta
    ? !!python/tuple
    - 0
    - 18
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id002
      flow: 187
      length: 1.0
      resource: null
      startNode: *id001
      trip: 18
      type: beta
  delta:
    ? !!python/tuple
    - 0
    - 0
    - 0
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: &id003 !!python/object:resource.Resource
        capacity: 20
        clas: 0
        emptySpeed: 1
        fixedCost: 60433
        initialLocation: &id006 !!python/object:node.Node
          clas: 0
          id: 0
          position:
          - 11
          - 65
          type: initial
        loadedSpeed: 1
        loadingTime: 11.666666666666668
        maxTrips: 0
        speed: 0
        timeToAvaiability: 11.666666666666668
        trip: 18
        unloadingTime: 8.166666666666668
        varCost: 68
      startNode: &id004 !!python/object:node.PickDropPoint
        clas: 0
        id: 0
        position:
        - 67
        - 63
        type: shelter
      trip: 0
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 1
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 1
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 2
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 2
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 3
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 3
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 4
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 4
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 5
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 5
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 6
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 6
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 7
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 7
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 8
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 8
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 9
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 9
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 10
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 10
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 11
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 11
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 12
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 12
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 13
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 13
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 14
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 14
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 15
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 15
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 16
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 16
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 17
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 17
      type: delta
    ? !!python/tuple
    - 0
    - 0
    - 18
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id002
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id004
      trip: 18
      type: delta
  epsilon:
    ? !!python/tuple
    - 0
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: &id005 !!python/object:node.Node
        clas: 0
        id: 1
        position:
        - 98
        - 50
        type: sink
      flow: 10
      length: 3.3
      resource: null
      startNode: *id004
      type: epsilon
  gamma:
    ? !!python/tuple
    - 0
    - 0
    - 0
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 0
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 1
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 1
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 2
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 2
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 3
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 3
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 4
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 4
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 5
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 5
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 6
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 6
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 7
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 7
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 8
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 8
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 9
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 9
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 10
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 10
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 11
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 11
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 12
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 12
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 13
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 13
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 14
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 14
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 15
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 15
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 16
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 16
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 17
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 17
      type: gamma
    ? !!python/tuple
    - 0
    - 0
    - 18
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 5
      endNode: *id004
      flow: 4.0
      length: 4.1
      resource: *id003
      startNode: *id002
      trip: 18
      type: gamma
  lmbda:
    ? !!python/tuple
    - 0
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 0
      endNode: *id005
      flow: 0
      length: 7.8
      resource: null
      startNode: *id001
      type: lmbda
  zeta:
    ? !!python/tuple
    - 0
    - 0
    - 0
    - 0
    : !!python/object:arc.Arc
      cost: 4
      endNode: *id002
      flow: 0
      length: 3.3
      resource: *id003
      startNode: *id006
      trip: 0
      type: zeta
nodes:
  area: &id008
  - *id001
  initial:
  - *id006
  pick_up:
  - *id002
  shelter:
  - *id004
  sink: *id005
  source: *id007
params:
  a: 1
  b: 1
  c: 1
  h: 1
  i: 1
  s: 1
  self: 0
resources:
- - *id003
scenarios:
- !!python/object:scenario.Scenario
  evaAreas: *id008
  evaDemand: 0
  lightLevel: 4
  loadingCoeff: 1.1666666666666667
  night: 0
  num_k: 19
  probability: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    AAAAAAAA8D8=
  rainLevel: 1
  severity: 3
  speedCoeff: 0.8833333333333333
  weather:
    light:
      drive:
      - 0
      - 0.05
      - 0.1
      - 0.15
      - 0.2
      loadingOps:
      - 0
      - 0.1
      - 0.2
      - 0.25
      - 0.3
    rain:
      drive:
      - 0
      - 0.1
      - 0.15
      - 0.25
      - 0.33
      loadingOps:
      - 0
      - 0.1
      - 0.2
      - 0.25
      - 0.3
    wind:
      drive:
      - 0
      - 0.05
      - 0.1
      - 0.15
      - 0.2
      loadingOps:
      - 0
      - 0.1
      - 0.2
      - 0.25
      - 0.3
  windLevel: 1
